pipeline {
    agent none
    parameters {
       string(name: 'Version', defaultValue: '', description: 'App version')
       booleanParam(name: 'executeTests', defaultValue: true, description: '')
    }
    stages {
        stage('Checkout on volumine') {
            agent any
            steps {
                script{
                    try{
                        sh 'docker volume create vol-in'
                        sh 'docker volume create vol-out'
                        sh 'rm * -r'
                        sh 'docker volume ls'

                        sh 'docker run -d --rm --name tmp -v vol-in:/vi alpine tail -f /dev/null'
                        dir('scm_cp') {
                            checkout scm
                            sh 'rm .git .github -r'
                            sh 'cat package.json'
                            sh 'docker cp . tmp:/vi/$BUILD_NUMBER'
                            sh 'docker stop tmp'
                        }
                    }
                    catch (Exception e) {
                        sh 'docker stop tmp'
                        throw new Exception(e.toString())
                    }
                }
            }
        }

        stage('Build') {
            agent {
                docker {
                    image 'node'
                    args '-v vol-in:/vi -v vol-out:/vo -v $WORKSPACE:/output'

                }
            }
            steps {
                sh 'ls /vi/$BUILD_NUMBER -al'
                dir('BLD') {
                    sh 'cp /vi/$BUILD_NUMBER/ . -r'
                    sh 'npm install --save --legacy-peer-deps'
                    sh 'npm run build'
                    sh 'cp . /output/pckg -r'
                }
            }
        }

        stage('Test') {
            agent {
                docker {
                    image 'node'
                    args '-v vol-in:/vi -v vol-out:/vo'

                }
            }
            when {
                expression {
                    params.executeTests
                }
            }

            
            steps {

                dir('BLD') {
                    sh 'npm run test:lint:md'
                    sh 'npm run test:lint:stylelint'
                    sh 'npm run test:lint:lockfile'
                    sh 'npm run test:html'
                    sh 'npm run test:unit'
                }

            }
        }

        stage('Deploy') {
            agent {
                docker {
                    image 'node'
                    args '-v vol-in:/vi -v vol-out:/vo'

                }
            }
            steps {

                dir('BLD') {
                    script {
                        try {
                            timeout(time: 1, unit: 'MINUTES') {
                                sh 'npm start'
                            }
                        } catch (Exception e) {
                            echo e.toString()
                            if(e.toString()=="org.jenkinsci.plugins.workflow.steps.FlowInterruptedException")
                            {
                                echo 'Deployed successfully!'
                            }else{
                                throw new Exception(e.toString())
                            }
                        }
                    }

                }

            }
        }
        

        stage('Publish') {
            agent {
                docker {
                    image 'node'
                    args '-v vol-in:/vi -v vol-out:/vo'
                }
            }
            steps {
                dir('pckg/$BUILD_NUMBER') { 
                    
                        sh 'git config --global user.email "dominila.l@gmail.com"'
                        sh 'git config --global user.name "ldidil"'
                        withEnv(["TOKEN=${GH_TOKEN}"]) {
                            sh 'git config remote.origin.url "https://${TOKEN}@github.com/werruse/nodejs.org.git"'
                        }
                        withEnv(["VER=${VERSION}"]){                
                        withEnv(["TOKEN=${NPMJS_TOKEN}"]) {
                            sh 'echo "//registry.npmjs.org/:_authToken=${TOKEN}" >> ~/.npmrc'
                        }
                        sh 'npm version ${VER}-build$BUILD_NUMBER'
                        sh 'npm publish'
                }
            }
        }
    }
}
