pipeline {
    agent any

	parameters {
		string(name: 'Version', defaultValue: '', description: 'App version')
	}

    stages {
  
        stage("build") {
            steps {
                echo "building.." 
                dir('CI'){
				sh 'docker build . -f builder.dockerfile -t builder'
                }
            }
        }

        stage('test') {
            steps {
			  sh 'docker build . -f test.dockerfile -t tester'
			  sh' docker run tester'
            }
        }
   } 
}